### ISSUE TITLE
npm error ELIFECYCLE

### ISSUE THREAD

**Issue by aanhlle** [ernestohegi/japanese-text-parser#185]
Hi so I get this issue when deploying the project.
I'm currently using lastest npm (v6.14.11)

The log is as below. Have tried some solutions here but didn't work so I report it here.
https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle

It seems some of the dependencies or start script has malfunctioned?

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle japanese-text-parser@1.0.0~predev: japanese-text-parser@1.0.0
6 info lifecycle japanese-text-parser@1.0.0~dev: japanese-text-parser@1.0.0
7 verbose lifecycle japanese-text-parser@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle japanese-text-parser@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Japanese text parser\japanese-text-parser-master\node_modules\.bin;C:\Users\Anh Le\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Program Files\Amazon Corretto\jdk11.0.9_12\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Calibre2;C:\Program Files\SourceGear\Common\DiffMerge;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\Anh Le\AppData\Local\Microsoft\WindowsApps;C:\Users\Anh Le\AppData\Local\atom\bin;C:\Users\Anh Le\AppData\Roaming\npm;C:\Users\Anh Le\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle japanese-text-parser@1.0.0~dev: CWD: E:\Japanese text parser\japanese-text-parser-master
10 silly lifecycle japanese-text-parser@1.0.0~dev: Args: [ '/d /s /c', 'NODE_ENV=development node index.js' ]
11 silly lifecycle japanese-text-parser@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle japanese-text-parser@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: japanese-text-parser@1.0.0 dev: `NODE_ENV=development node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid japanese-text-parser@1.0.0
15 verbose cwd E:\Japanese text parser\japanese-text-parser-master
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v14.15.5
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error japanese-text-parser@1.0.0 dev: `NODE_ENV=development node index.js`
22 error Exit status 1
23 error Failed at the japanese-text-parser@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by 2inshix** [comment]
Hello, I get the exact same error. Did anyone find a solution? Appreciated.
E:\japanese-text-parser-master>npm run dev

> japanese-text-parser@1.0.0 dev E:\japanese-text-parser-master
> PORT=4000 NODE_ENV=development node index.js

'PORT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! japanese-text-parser@1.0.0 dev: `PORT=4000 NODE_ENV=development node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the japanese-text-parser@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-08-01T16_28_45_508Z-debug.log
